//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: godaiquest.proto
namespace godaiquest
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AddUser")]
  public partial class AddUser : global::ProtoBuf.IExtensible
  {
    public AddUser() {}
    
    private string _mail_address = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mail_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mail_address
    {
      get { return _mail_address; }
      set { _mail_address = value; }
    }
    private string _user_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_name
    {
      get { return _user_name; }
      set { _user_name = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _user_folder = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"user_folder", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_folder
    {
      get { return _user_folder; }
      set { _user_folder = value; }
    }
    private string _computer_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"computer_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string computer_name
    {
      get { return _computer_name; }
      set { _computer_name = value; }
    }
    private byte[] _user_image = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"user_image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] user_image
    {
      get { return _user_image; }
      set { _user_image = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Login")]
  public partial class Login : global::ProtoBuf.IExtensible
  {
    public Login() {}
    
    private string _mail_address = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mail_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mail_address
    {
      get { return _mail_address; }
      set { _mail_address = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private uint _client_version = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"client_version", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint client_version
    {
      get { return _client_version; }
      set { _client_version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GetDungeon")]
  public partial class GetDungeon : global::ProtoBuf.IExtensible
  {
    public GetDungeon() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _dungeon_number = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dungeon_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dungeon_number
    {
      get { return _dungeon_number; }
      set { _dungeon_number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DungeonInfo")]
  public partial class DungeonInfo : global::ProtoBuf.IExtensible
  {
    public DungeonInfo() {}
    
    private byte[] _dungeon = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dungeon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] dungeon
    {
      get { return _dungeon; }
      set { _dungeon = value; }
    }
    private int _size_x = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"size_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int size_x
    {
      get { return _size_x; }
      set { _size_x = value; }
    }
    private int _size_y = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"size_y", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int size_y
    {
      get { return _size_y; }
      set { _size_y = value; }
    }
    private int _dungeon_number = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dungeon_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dungeon_number
    {
      get { return _dungeon_number; }
      set { _dungeon_number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ImagePair")]
  public partial class ImagePair : global::ProtoBuf.IExtensible
  {
    public ImagePair() {}
    
    private int _number = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private byte[] _image = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] image
    {
      get { return _image; }
      set { _image = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _owner = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"owner", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int owner
    {
      get { return _owner; }
      set { _owner = value; }
    }
    private long _created = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"created", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long created
    {
      get { return _created; }
      set { _created = value; }
    }
    private bool _can_item_image = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"can_item_image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool can_item_image
    {
      get { return _can_item_image; }
      set { _can_item_image = value; }
    }
    private bool _new_image = default(bool);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"new_image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool new_image
    {
      get { return _new_image; }
      set { _new_image = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ImagePairDic")]
  public partial class ImagePairDic : global::ProtoBuf.IExtensible
  {
    public ImagePairDic() {}
    
    private uint _index = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint index
    {
      get { return _index; }
      set { _index = value; }
    }
    private godaiquest.ImagePair _imagepair = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"imagepair", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public godaiquest.ImagePair imagepair
    {
      get { return _imagepair; }
      set { _imagepair = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DungeonBlockImageInfo")]
  public partial class DungeonBlockImageInfo : global::ProtoBuf.IExtensible
  {
    public DungeonBlockImageInfo() {}
    
    private uint _max_image_num = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"max_image_num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint max_image_num
    {
      get { return _max_image_num; }
      set { _max_image_num = value; }
    }
    private readonly global::System.Collections.Generic.List<godaiquest.ImagePairDic> _image_dic = new global::System.Collections.Generic.List<godaiquest.ImagePairDic>();
    [global::ProtoBuf.ProtoMember(2, Name=@"image_dic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.ImagePairDic> image_dic
    {
      get { return _image_dic; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectAttr")]
  public partial class ObjectAttr : global::ProtoBuf.IExtensible
  {
    public ObjectAttr() {}
    
    private int _object_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"object_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int object_id
    {
      get { return _object_id; }
      set { _object_id = value; }
    }
    private bool _can_walk = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"can_walk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool can_walk
    {
      get { return _can_walk; }
      set { _can_walk = value; }
    }
    private int _item_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private bool _bNew = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"bNew", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bNew
    {
      get { return _bNew; }
      set { _bNew = value; }
    }
    private int _command = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"command", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int command
    {
      get { return _command; }
      set { _command = value; }
    }
    private int _command_sub = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"command_sub", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int command_sub
    {
      get { return _command_sub; }
      set { _command_sub = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectAttrDic")]
  public partial class ObjectAttrDic : global::ProtoBuf.IExtensible
  {
    public ObjectAttrDic() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private godaiquest.ObjectAttr _object_attr = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"object_attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public godaiquest.ObjectAttr object_attr
    {
      get { return _object_attr; }
      set { _object_attr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ObjectAttrInfo")]
  public partial class ObjectAttrInfo : global::ProtoBuf.IExtensible
  {
    public ObjectAttrInfo() {}
    
    private int _new_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"new_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int new_id
    {
      get { return _new_id; }
      set { _new_id = value; }
    }
    private readonly global::System.Collections.Generic.List<godaiquest.ObjectAttrDic> _object_attr_dic = new global::System.Collections.Generic.List<godaiquest.ObjectAttrDic>();
    [global::ProtoBuf.ProtoMember(2, Name=@"object_attr_dic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.ObjectAttrDic> object_attr_dic
    {
      get { return _object_attr_dic; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tile")]
  public partial class Tile : global::ProtoBuf.IExtensible
  {
    public Tile() {}
    
    private ulong _tile_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tile_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong tile_id
    {
      get { return _tile_id; }
      set { _tile_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TileDic")]
  public partial class TileDic : global::ProtoBuf.IExtensible
  {
    public TileDic() {}
    
    private ulong _index = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong index
    {
      get { return _index; }
      set { _index = value; }
    }
    private godaiquest.Tile _tile = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tile", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public godaiquest.Tile tile
    {
      get { return _tile; }
      set { _tile = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TileInfo")]
  public partial class TileInfo : global::ProtoBuf.IExtensible
  {
    public TileInfo() {}
    
    private readonly global::System.Collections.Generic.List<godaiquest.TileDic> _tile_dic = new global::System.Collections.Generic.List<godaiquest.TileDic>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tile_dic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.TileDic> tile_dic
    {
      get { return _tile_dic; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetDungeon")]
  public partial class SetDungeon : global::ProtoBuf.IExtensible
  {
    public SetDungeon() {}
    
    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private int _dungeon_number = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dungeon_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dungeon_number
    {
      get { return _dungeon_number; }
      set { _dungeon_number = value; }
    }
    private godaiquest.DungeonInfo _dungeon_info = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dungeon_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public godaiquest.DungeonInfo dungeon_info
    {
      get { return _dungeon_info; }
      set { _dungeon_info = value; }
    }
    private godaiquest.DungeonBlockImageInfo _images = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"images", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public godaiquest.DungeonBlockImageInfo images
    {
      get { return _images; }
      set { _images = value; }
    }
    private godaiquest.ObjectAttrInfo _object_info = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"object_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public godaiquest.ObjectAttrInfo object_info
    {
      get { return _object_info; }
      set { _object_info = value; }
    }
    private godaiquest.TileInfo _tile_info = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"tile_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public godaiquest.TileInfo tile_info
    {
      get { return _tile_info; }
      set { _tile_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TilePaletteImageSet")]
  public partial class TilePaletteImageSet : global::ProtoBuf.IExtensible
  {
    public TilePaletteImageSet() {}
    
    private ulong _tile_id = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tile_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong tile_id
    {
      get { return _tile_id; }
      set { _tile_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TilePalette")]
  public partial class TilePalette : global::ProtoBuf.IExtensible
  {
    public TilePalette() {}
    
    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private readonly global::System.Collections.Generic.List<godaiquest.TilePaletteImageSet> _image_set = new global::System.Collections.Generic.List<godaiquest.TilePaletteImageSet>();
    [global::ProtoBuf.ProtoMember(2, Name=@"image_set", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.TilePaletteImageSet> image_set
    {
      get { return _image_set; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SetBlockImagePalette")]
  public partial class SetBlockImagePalette : global::ProtoBuf.IExtensible
  {
    public SetBlockImagePalette() {}
    
    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private godaiquest.TilePalette _tile_palette = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tile_palette", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public godaiquest.TilePalette tile_palette
    {
      get { return _tile_palette; }
      set { _tile_palette = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AUser")]
  public partial class AUser : global::ProtoBuf.IExtensible
  {
    public AUser() {}
    
    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _mail_address = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mail_address", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mail_address
    {
      get { return _mail_address; }
      set { _mail_address = value; }
    }
    private string _user_name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"user_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string user_name
    {
      get { return _user_name; }
      set { _user_name = value; }
    }
    private byte[] _user_image = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"user_image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] user_image
    {
      get { return _user_image; }
      set { _user_image = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AUserDic")]
  public partial class AUserDic : global::ProtoBuf.IExtensible
  {
    public AUserDic() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private godaiquest.AUser _auser = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"auser", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public godaiquest.AUser auser
    {
      get { return _auser; }
      set { _auser = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfo")]
  public partial class UserInfo : global::ProtoBuf.IExtensible
  {
    public UserInfo() {}
    
    private readonly global::System.Collections.Generic.List<godaiquest.AUserDic> _uesr_dic = new global::System.Collections.Generic.List<godaiquest.AUserDic>();
    [global::ProtoBuf.ProtoMember(1, Name=@"uesr_dic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.AUserDic> uesr_dic
    {
      get { return _uesr_dic; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AItem")]
  public partial class AItem : global::ProtoBuf.IExtensible
  {
    public AItem() {}
    
    private int _item_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private int _item_image_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"item_image_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int item_image_id
    {
      get { return _item_image_id; }
      set { _item_image_id = value; }
    }
    private string _header_string = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"header_string", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string header_string
    {
      get { return _header_string; }
      set { _header_string = value; }
    }
    private byte[] _header_image = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"header_image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] header_image
    {
      get { return _header_image; }
      set { _header_image = value; }
    }
    private bool _bNew = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"bNew", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bNew
    {
      get { return _bNew; }
      set { _bNew = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AItemDic")]
  public partial class AItemDic : global::ProtoBuf.IExtensible
  {
    public AItemDic() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private godaiquest.AItem _aitem = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"aitem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public godaiquest.AItem aitem
    {
      get { return _aitem; }
      set { _aitem = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemInfo")]
  public partial class ItemInfo : global::ProtoBuf.IExtensible
  {
    public ItemInfo() {}
    
    private readonly global::System.Collections.Generic.List<godaiquest.AItemDic> _aitem_dic = new global::System.Collections.Generic.List<godaiquest.AItemDic>();
    [global::ProtoBuf.ProtoMember(1, Name=@"aitem_dic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.AItemDic> aitem_dic
    {
      get { return _aitem_dic; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ALocation")]
  public partial class ALocation : global::ProtoBuf.IExtensible
  {
    public ALocation() {}
    
    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private int _ix = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ix", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ix
    {
      get { return _ix; }
      set { _ix = value; }
    }
    private int _iy = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"iy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iy
    {
      get { return _iy; }
      set { _iy = value; }
    }
    private int _dungeon_user_id = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dungeon_user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dungeon_user_id
    {
      get { return _dungeon_user_id; }
      set { _dungeon_user_id = value; }
    }
    private int _dungeon_number = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dungeon_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dungeon_number
    {
      get { return _dungeon_number; }
      set { _dungeon_number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ALocationDic")]
  public partial class ALocationDic : global::ProtoBuf.IExtensible
  {
    public ALocationDic() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private godaiquest.ALocation _alocation = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"alocation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public godaiquest.ALocation alocation
    {
      get { return _alocation; }
      set { _alocation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LocationInfo")]
  public partial class LocationInfo : global::ProtoBuf.IExtensible
  {
    public LocationInfo() {}
    
    private readonly global::System.Collections.Generic.List<godaiquest.ALocationDic> _alocation_dic = new global::System.Collections.Generic.List<godaiquest.ALocationDic>();
    [global::ProtoBuf.ProtoMember(1, Name=@"alocation_dic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.ALocationDic> alocation_dic
    {
      get { return _alocation_dic; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Signal")]
  public partial class Signal : global::ProtoBuf.IExtensible
  {
    public Signal() {}
    
    private int _signal = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"signal", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int signal
    {
      get { return _signal; }
      set { _signal = value; }
    }
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _ix = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ix", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ix
    {
      get { return _ix; }
      set { _ix = value; }
    }
    private int _iy = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"iy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iy
    {
      get { return _iy; }
      set { _iy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SignalQueue")]
  public partial class SignalQueue : global::ProtoBuf.IExtensible
  {
    public SignalQueue() {}
    
    private string _system_message = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"system_message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string system_message
    {
      get { return _system_message; }
      set { _system_message = value; }
    }
    private readonly global::System.Collections.Generic.List<godaiquest.Signal> _signals = new global::System.Collections.Generic.List<godaiquest.Signal>();
    [global::ProtoBuf.ProtoMember(2, Name=@"signals", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.Signal> signals
    {
      get { return _signals; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IslandGround")]
  public partial class IslandGround : global::ProtoBuf.IExtensible
  {
    public IslandGround() {}
    
    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private int _ix1 = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ix1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ix1
    {
      get { return _ix1; }
      set { _ix1 = value; }
    }
    private int _iy1 = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"iy1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iy1
    {
      get { return _iy1; }
      set { _iy1 = value; }
    }
    private int _ix2 = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ix2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int ix2
    {
      get { return _ix2; }
      set { _ix2 = value; }
    }
    private int _iy2 = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"iy2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int iy2
    {
      get { return _iy2; }
      set { _iy2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IslandGroundInfo")]
  public partial class IslandGroundInfo : global::ProtoBuf.IExtensible
  {
    public IslandGroundInfo() {}
    
    private readonly global::System.Collections.Generic.List<godaiquest.IslandGround> _ground_list = new global::System.Collections.Generic.List<godaiquest.IslandGround>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ground_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.IslandGround> ground_list
    {
      get { return _ground_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AMessage")]
  public partial class AMessage : global::ProtoBuf.IExtensible
  {
    public AMessage() {}
    
    private int _uesr_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uesr_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int uesr_id
    {
      get { return _uesr_id; }
      set { _uesr_id = value; }
    }
    private string _message = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AMessageDic")]
  public partial class AMessageDic : global::ProtoBuf.IExtensible
  {
    public AMessageDic() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private godaiquest.AMessage _amessage = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"amessage", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public godaiquest.AMessage amessage
    {
      get { return _amessage; }
      set { _amessage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MessageInfo")]
  public partial class MessageInfo : global::ProtoBuf.IExtensible
  {
    public MessageInfo() {}
    
    private readonly global::System.Collections.Generic.List<godaiquest.AMessageDic> _message_dic = new global::System.Collections.Generic.List<godaiquest.AMessageDic>();
    [global::ProtoBuf.ProtoMember(1, Name=@"message_dic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.AMessageDic> message_dic
    {
      get { return _message_dic; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"APickuped")]
  public partial class APickuped : global::ProtoBuf.IExtensible
  {
    public APickuped() {}
    
    private int _item_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private long _date_time = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"date_time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long date_time
    {
      get { return _date_time; }
      set { _date_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PickupedInfo")]
  public partial class PickupedInfo : global::ProtoBuf.IExtensible
  {
    public PickupedInfo() {}
    
    private readonly global::System.Collections.Generic.List<godaiquest.APickuped> _apickuped = new global::System.Collections.Generic.List<godaiquest.APickuped>();
    [global::ProtoBuf.ProtoMember(1, Name=@"apickuped", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.APickuped> apickuped
    {
      get { return _apickuped; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Ashiatolog")]
  public partial class Ashiatolog : global::ProtoBuf.IExtensible
  {
    public Ashiatolog() {}
    
    private readonly global::System.Collections.Generic.List<string> _alog = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"alog", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> alog
    {
      get { return _alog; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemArticle")]
  public partial class ItemArticle : global::ProtoBuf.IExtensible
  {
    public ItemArticle() {}
    
    private int _item_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private int _article_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"article_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int article_id
    {
      get { return _article_id; }
      set { _article_id = value; }
    }
    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private string _contents = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"contents", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string contents
    {
      get { return _contents; }
      set { _contents = value; }
    }
    private long _cretae_time = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cretae_time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long cretae_time
    {
      get { return _cretae_time; }
      set { _cretae_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemArticleDic")]
  public partial class ItemArticleDic : global::ProtoBuf.IExtensible
  {
    public ItemArticleDic() {}
    
    private int _index = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private godaiquest.ItemArticle _item_article = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"item_article", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public godaiquest.ItemArticle item_article
    {
      get { return _item_article; }
      set { _item_article = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemArticleInfo")]
  public partial class ItemArticleInfo : global::ProtoBuf.IExtensible
  {
    public ItemArticleInfo() {}
    
    private int _item_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private readonly global::System.Collections.Generic.List<godaiquest.ItemArticleDic> _item_article_dic = new global::System.Collections.Generic.List<godaiquest.ItemArticleDic>();
    [global::ProtoBuf.ProtoMember(2, Name=@"item_article_dic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.ItemArticleDic> item_article_dic
    {
      get { return _item_article_dic; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterDic")]
  public partial class MonsterDic : global::ProtoBuf.IExtensible
  {
    public MonsterDic() {}
    
    private int _key = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int key
    {
      get { return _key; }
      set { _key = value; }
    }
    private int _value = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MonsterInfo")]
  public partial class MonsterInfo : global::ProtoBuf.IExtensible
  {
    public MonsterInfo() {}
    
    private readonly global::System.Collections.Generic.List<godaiquest.MonsterDic> _monster_dic = new global::System.Collections.Generic.List<godaiquest.MonsterDic>();
    [global::ProtoBuf.ProtoMember(1, Name=@"monster_dic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.MonsterDic> monster_dic
    {
      get { return _monster_dic; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RDReadItemDic")]
  public partial class RDReadItemDic : global::ProtoBuf.IExtensible
  {
    public RDReadItemDic() {}
    
    private int _item_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RDReadItemInfo")]
  public partial class RDReadItemInfo : global::ProtoBuf.IExtensible
  {
    public RDReadItemInfo() {}
    
    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private readonly global::System.Collections.Generic.List<godaiquest.RDReadItemDic> _read_item_dic = new global::System.Collections.Generic.List<godaiquest.RDReadItemDic>();
    [global::ProtoBuf.ProtoMember(2, Name=@"read_item_dic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.RDReadItemDic> read_item_dic
    {
      get { return _read_item_dic; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ARealMonster")]
  public partial class ARealMonster : global::ProtoBuf.IExtensible
  {
    public ARealMonster() {}
    
    private int _monster_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"monster_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int monster_id
    {
      get { return _monster_id; }
      set { _monster_id = value; }
    }
    private string _monster_name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"monster_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string monster_name
    {
      get { return _monster_name; }
      set { _monster_name = value; }
    }
    private byte[] _monster_image = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"monster_image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] monster_image
    {
      get { return _monster_image; }
      set { _monster_image = value; }
    }
    private int _monster_expvalue = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"monster_expvalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int monster_expvalue
    {
      get { return _monster_expvalue; }
      set { _monster_expvalue = value; }
    }
    private string _monster_spell = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"monster_spell", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string monster_spell
    {
      get { return _monster_spell; }
      set { _monster_spell = value; }
    }
    private int _monster_src_id = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"monster_src_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int monster_src_id
    {
      get { return _monster_src_id; }
      set { _monster_src_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RealMonsterInfo")]
  public partial class RealMonsterInfo : global::ProtoBuf.IExtensible
  {
    public RealMonsterInfo() {}
    
    private readonly global::System.Collections.Generic.List<godaiquest.ARealMonster> _real_monster = new global::System.Collections.Generic.List<godaiquest.ARealMonster>();
    [global::ProtoBuf.ProtoMember(1, Name=@"real_monster", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.ARealMonster> real_monster
    {
      get { return _real_monster; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ARealMonsterLocation")]
  public partial class ARealMonsterLocation : global::ProtoBuf.IExtensible
  {
    public ARealMonsterLocation() {}
    
    private int _monster_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"monster_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int monster_id
    {
      get { return _monster_id; }
      set { _monster_id = value; }
    }
    private int _monster_ix = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"monster_ix", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int monster_ix
    {
      get { return _monster_ix; }
      set { _monster_ix = value; }
    }
    private int _monster_iy = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"monster_iy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int monster_iy
    {
      get { return _monster_iy; }
      set { _monster_iy = value; }
    }
    private int _dungeon_number = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dungeon_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int dungeon_number
    {
      get { return _dungeon_number; }
      set { _dungeon_number = value; }
    }
    private int _monster_src_id = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"monster_src_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int monster_src_id
    {
      get { return _monster_src_id; }
      set { _monster_src_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RealMonsterLocationInfo")]
  public partial class RealMonsterLocationInfo : global::ProtoBuf.IExtensible
  {
    public RealMonsterLocationInfo() {}
    
    private readonly global::System.Collections.Generic.List<godaiquest.ARealMonsterLocation> _location_list = new global::System.Collections.Generic.List<godaiquest.ARealMonsterLocation>();
    [global::ProtoBuf.ProtoMember(1, Name=@"location_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.ARealMonsterLocation> location_list
    {
      get { return _location_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AKeywordItem")]
  public partial class AKeywordItem : global::ProtoBuf.IExtensible
  {
    public AKeywordItem() {}
    
    private int _item_priority = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"item_priority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int item_priority
    {
      get { return _item_priority; }
      set { _item_priority = value; }
    }
    private int _item_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AKeyword")]
  public partial class AKeyword : global::ProtoBuf.IExtensible
  {
    public AKeyword() {}
    
    private int _keyword_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"keyword_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int keyword_id
    {
      get { return _keyword_id; }
      set { _keyword_id = value; }
    }
    private string _keyword = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"keyword", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string keyword
    {
      get { return _keyword; }
      set { _keyword = value; }
    }
    private int _keyword_priority = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"keyword_priority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int keyword_priority
    {
      get { return _keyword_priority; }
      set { _keyword_priority = value; }
    }
    private readonly global::System.Collections.Generic.List<godaiquest.AKeywordItem> _keyword_item_set = new global::System.Collections.Generic.List<godaiquest.AKeywordItem>();
    [global::ProtoBuf.ProtoMember(4, Name=@"keyword_item_set", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.AKeywordItem> keyword_item_set
    {
      get { return _keyword_item_set; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KeywordUserInfo")]
  public partial class KeywordUserInfo : global::ProtoBuf.IExtensible
  {
    public KeywordUserInfo() {}
    
    private int _user_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int user_id
    {
      get { return _user_id; }
      set { _user_id = value; }
    }
    private readonly global::System.Collections.Generic.List<godaiquest.AKeyword> _keyword_set = new global::System.Collections.Generic.List<godaiquest.AKeyword>();
    [global::ProtoBuf.ProtoMember(2, Name=@"keyword_set", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.AKeyword> keyword_set
    {
      get { return _keyword_set; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AItemTime")]
  public partial class AItemTime : global::ProtoBuf.IExtensible
  {
    public AItemTime() {}
    
    private int _item_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private long _created = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"created", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long created
    {
      get { return _created; }
      set { _created = value; }
    }
    private long _last_modified = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"last_modified", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long last_modified
    {
      get { return _last_modified; }
      set { _last_modified = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ItemTimeInfo")]
  public partial class ItemTimeInfo : global::ProtoBuf.IExtensible
  {
    public ItemTimeInfo() {}
    
    private readonly global::System.Collections.Generic.List<godaiquest.AItemTime> _item_time_list = new global::System.Collections.Generic.List<godaiquest.AItemTime>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item_time_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<godaiquest.AItemTime> item_time_list
    {
      get { return _item_time_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}